---
- include_tasks: setup.yml

- include_tasks: groups.yml

- include_tasks: users.yml

# - include_tasks: user_groups.yml

# - include_tasks: deployer.yml

# - name: Remove user from deployer group
