---
# Create the user if:
# - is present and hosts is empty or undefined
# - is present and current node is in hosts
- name: Create users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.comment | default('User {{item.username}}') }}"
    password: "{{ item.password | default('!') }}"
    state: "{{ item.state | default('present') }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    group: "{{ item.group | default(users_default_group) }}"
  with_items: '{{ users }}'
  when: >
    item.username is defined
    and
    (
      item.state is not defined or item.state != "absent"
    )
    and
    (
      (
        item.hosts is not defined
        or item.hosts == ""
        or item.hosts == []
        or item.hosts == {}
      )
      or
      (
        item.hosts is defined
        and
        (
          inventory_hostname|in_dict_multilist(item.hosts)
          or group_names|in_dict_multilist(item.hosts)
        )
      )
    )

# Remove the user if:
# - is absent and hosts is empty
# - is not absent and hosts is not empty and current node is not in hosts
- name: Remove users
  user: name={{ item.username }} state=absent
  with_items: '{{ users }}'
  when: >
    item.username is defined and
    (
      (
        item.state is defined and item.state == "absent" and
        (
          item.hosts is not defined
          or item.hosts == ""
          or item.hosts == []
          or item.hosts == {}
          or inventory_hostname in item.hosts
          or group_names in item.hosts
        )
      )
      or
      (
        (item.state is not defined or item.state != "absent")
        and item.hosts is defined
        and item.hosts != "" and item.hosts != [] and item.hosts != {}
        and inventory_hostname|in_dict_multilist(item.hosts) == False
        and group_names|in_dict_multilist(item.hosts) == False
      )
    )

- name: Add SSH-keys to users
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - keys.active
    - flags:
      skip_missing: True
  when: >
    item.0.username is defined and (
      item.0.state is not defined or item.0.state != "absent"
    )
    and (
      (item.0.superadmin is defined and item.0.superadmin == True)
      or (
        item.0.hosts is defined and (
          inventory_hostname|in_dict_multilist(item.0.hosts)
          or group_names|in_dict_multilist(item.0.hosts)
        )
      )
    )

- name: Remove disabled SSH-keys from active users
  authorized_key:
    user: "{{ item.0.username }}"
    key: "{{ item.1 }}"
    state: absent
  with_subelements:
    - "{{ users }}"
    - keys.disabled
    - flags:
      skip_missing: True
  when: >
    item.0.username is defined and (
      item.0.state is not defined or item.0.state != "absent"
    )
    and (
      (item.0.superadmin is defined and item.0.superadmin == True)
      or (
        item.0.hosts is defined and (
          inventory_hostname|in_dict_multilist(item.0.hosts)
          or group_names|in_dict_multilist(item.0.hosts)
        )
      )
    )
